---
title: "STAT 385 Statistics Programming Methods - Fall 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Homework 1
### Due: Monday September 7, 2020 11:59 pm US Central Time
#### Created by Christopher Kinson

Grading Rubric (per question):  
2 points if complete and correct  
1 point if incomplete or incorrect  
0 points if no attempt made  


**Retrieving your work**

This and all future homework files are written in RMarkdown (.Rmd). The .Rmd file will exist in the `homework` directory within the `course-materials` repo, i.e. `course-materials/homework` in GitHub. You must **pull** the `course-materials` repo first to ensure that you have the most updated version of all course materials and files. After pulling the repo, the homework file will be in the homework directory. You must save the homework file into your individual GitHub repo (the one named as your netID). 

**Submitting your work**

In your individual repo (the one named as your netID), you are to submit ***two*** files:

a. Your reproducible document file (.Rmd) which should be saved as hw#_netID.Rmd. For example, my homework 1 file would be saved as hw1_kinson2.Rmd.

b. Your rendered reproducible document file (.html) which should be saved as hw#_netID.html. For example, my homework 1 file would be saved as hw1_kinson2.html.

You have an unlimited number of submissions, but only the latest proper submission (commit and push) will be viewed and graded. Remember the .Rmd file needs to render properly to .html before submitting. 


***


*The following problems should be completed by you as an individual. If any problem asks you a particular question, be sure to answer it completely (with code, written sentences, or both). Written sentences should not appear in code chunks or code cells. Written sentences should appear in Markdown syntax unless specifically stated otherwise. When students get stuck on a homework problem, students should ask the question in the Issues page in GitHub. Do not change anything in this file above the double line.*


***
***


### Use R for this entire homework assignment. Use the URLs to access the data. Functions or programming ideas outside of the topics/ideas covered thus far are not allowed. The `subset` function is never allowed in this course.

1. (Markdown) Using Markdown syntax, make a numbered list with your first name in normal text as the first item and your last name in bold text as the second item. 


2. (Syllabus, Markdown) All assignments are assumed to be in which time zone? 


3. (GitHub, Markdown) Are merge conflicts able to be resolved? Write Yes or No in bold text.


4. (RMarkdown, R Simple manipulations, R Numbers and vectors) Using RMarkdown, determine if these numbers are prime or not:

  a. 7919
  
  b. 111
  
  c. 777


5. (RMarkdown, R Simple manipulations, R Numbers and vectors) Using RMarkdown, calculate the following:

  a. 6 ÷2(1 + 2)

  b. 9 - 3 ÷ 1/3 + 1

  c. -10 ÷ (20 ÷ 2² × 5 ÷ 5) × 8 - 2


6. (RMarkdown, R Simple manipulations, R Numbers and vectors) Using RMarkdown, reproduce the result.
``` 
"happy 1"  "happy 2"  "happy 3"  "happy 4"  "happy 5" 
"happy 6"  "happy 7"  "happy 8"  "happy 9"  "happy 10"
"happy 1"  "happy 2"  "happy 3"  "happy 4"  "happy 5" 
"happy 6"  "happy 7"  "happy 8"  "happy 9"  "happy 10"
```


7. (RMarkdown, R Simple manipulations, R Numbers and vectors) Create a vector of length 15 that contains the number 9 in the ninth place and zeroes otherwise.


8. (RMarkdown, R Numbers and vectors) Using RMarkdown and the vector `X` with the code `set.seed(385); X <- rnorm(10)` compute the following statistics for `X` by only using computations (no functions) and the formulas as a guide:  

  a. mean $\bar{x}=\sum_{i=1}^{N} x_i/N$   
    
  b. squared deviations from the mean $(x_i-\bar{x})^2$ 
   
  c. sum of squared deviations from the mean $\sum_{i=1}^{N}(x_i-\bar{x})^2$ 


9. (RMarkdown, R Numbers and vectors) Using RMarkdown and the vector `X` with the code `set.seed(385); X <- rnorm(10)` compute the following statistics for `X` using any of the functions `length()`, `mean()`, and `sum()` and the formulas as a guide:  

  a. mean $\bar{x}=\sum_{i=1}^{N} x_i/N$   
    
  b. squared deviations from the mean $(x_i-\bar{x})^2$ 
  
  c. sum of squared deviations from the mean $\sum_{i=1}^{N}(x_i-\bar{x})^2$   


10. (GitHub) When you have completed all questions above, make a **commit** with the message "All done". After the commit is successful, **push** the completed file to your personal repo.